import Head from "next/head";
import React from "react";
import styles from "./MainLayout.module.css";

interface props {
    children: JSX.Element | JSX.Element[];
}

export const MainLayout = ({ children }: props) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.name}>{children}</main>

            <footer className={styles.footer}>
                <p>Powered by Alberto Castel</p>
            </footer>
        </div>
    );
};
